Ext.ns("dnet");
dnet.Translation = {
	appmenuitem : {
		about__lbl : "Despre DNet",
		appmenus__lbl : "Meniuri aplicaţie",
		bookmark__lbl : "Marcaje",
		calendar__lbl : "Calendar",
		changepswd__lbl : "Schimbă parola",
		client__lbl : "Client",
		dbchangelog__lbl : "Schimbari baza de date",
		frameInspector__lbl : "Inspector cadru",
		help__lbl : "Ajutor",
		home__lbl : "Acasă",
		lang__lbl : "Limbă",
		lock__lbl : "Blochează",
		logout__lbl : "Închide",
		managebookmark__lbl : "Gestionare",
		myaccount__lbl : "Contul meu",
		mysettings__lbl : "Setările mele",
		session__lbl : "Sesiune",
		theme__lbl : "Stil",
		theme_access__lbl : "Negru",
		theme_aqua__lbl : "Aqua",
		theme_blue__lbl : "Albastru",
		theme_capuccino__lbl : "Capuccino",
		theme_gray__lbl : "Gri",
		user__lbl : "Utilizator",
		userprefs__lbl : "Preferinţe",
		version__lbl : "Versiune"
	},
	dcvgrid : {
		btn_bulkedit_tlp : "Modifică înregistrările selectate",
		btn_perspective_tlp : "Layout-uri salvate",
		btn_perspective_txt : "Layout",
		bulkedit_run : "Aplică modificările",
		bulkedit_title : "Modifică înregistrările",
		exp_btn : "Export",
		exp_col_all : "Toate din listă",
		exp_col_all2 : "Toate disponibile",
		exp_col_visible : "Vizibile în listă",
		exp_columns : "Coloane",
		exp_format : "Format",
		exp_layout : "Orientare",
		exp_rec_all : "Toate inregistrările",
		exp_rec_current : "Înregistrarea curentă",
		exp_rec_sel : "Înregistrările selectate",
		exp_records : "Înregistrări",
		exp_run : "Exportă",
		exp_title : "Export date",
		filter_apply : "Aplică",
		filter_clear : "Anulează",
		filter_title : "Filtrare avansată",
		imp_btn : "Import",
		imp_file : "Fișier",
		imp_format : "Format",
		imp_notes : "Prima linie din fișier este ignorată. Se presupune că este linia cu anteturi.",
		imp_notes_lbl : "Observatii",
		imp_run : "Execută",
		imp_strgy : "Strategie",
		imp_strgy_bean : "Denumiri tehnice( campurile din fișier au aceleași anteturi ca și modelul de date al listei - vezi export )",
		imp_strgy_pos : "Layout listă( Coloanele vizibile din listă reprezintă campurile din fișier în aceeași ordine. )",
		imp_title : "Import date",
		layout_applySelected : "Aplică selectia",
		layout_mylayouts : "Alegeti layout existent",
		layout_name : "Salvează layout curent",
		layout_saveCurrent : "Salvează cel curent",
		layout_title : "My layouts",
		print_run : "Tipăreste",
		print_title : "Tipăreste date",
		sort_btn : "Sortare",
		sort_run : "Aplică",
		sort_title : "Sortează după mai multe coloane"
	},
	ds : {
		active : "Activ",
		bpartnerCode : "Terţ",
		bpartnerId : "Terţ(ID)",
		clientId : "Client",
		code : "Cod",
		createdAt : "Creat la",
		createdBy : "Creat de",
		description : "Descriere",
		id : "ID",
		modifiedAt : "Modificat la",
		modifiedBy : "Modificat de",
		name : "Denumire",
		notes : "Observaţii",
		statusId : "Stare(ID)",
		statusName : "Stare",
		valid : "Valid",
		version : "Versiune"
	},
	exception : {
		DIRTY_DATA_FOUND : "Salvaţi sau anulaţi mai întai modificările făcute.",
		NAVIGATE_AFTER_LAST : "La ultima înregistrare disponibilă.",
		NAVIGATE_BEFORE_FIRST : "La prima înregistrare disponibilă.",
		NO_CURRENT_RECORD : "Nu există înregistrare curentă pentru acţiunea solicitată.",
		NO_SELECTED_RECORDS : "Nu există înregistrări selectate pentru acţiunea solicitată.",
		PARENT_RECORD_NEW : "Acţiunea solicitată este in contextul unei înregistrări noi.<br> Salvaţi sau anulaţi mai întai inregistrarea părinte."
	},
	msg : {
		bool_false : "Nu",
		bool_true : "Da",
		chpswd_btn : "Schimbă parola",
		chpswd_nomatch : "Noua parolă nu este confirmată corect. Introduceţi din nou campul `Confirmare parolă`.",
		chpswd_pswd1 : "Parola nouă",
		chpswd_pswd2 : "Confirmare parolă",
		chpswd_success : "Parola a fost schimbată.<BR> Folosiţi noua parolă la următoarea autentificare.",
		chpswd_title : "Schimbare parolă",
		dc_confirm_action : "Confirmare acţiune",
		dc_confirm_delete_selection : "Doriţi să ștergeţi inregistrările selectate? ",
		grid_emptytext : "Nu s-au găsit înregistrări care să corespundă criteriilor de filtrare.",
		initialize : "Iniţializare",
		loading : "Încarcă",
		login_btn : "Conectare",
		login_client : "Client",
		login_lang : "Limbă",
		login_pswd : "Parolă",
		login_title : "Autentificare",
		login_user : "Utilizator",
		no_current_record : "Nu există înregistrare curentă",
		no_current_record_for_report : "Nu există înregistrare curentă.<br> Nu se poate apela raportul `{1}` fără o înregistrare curentă care să furnizeze valorile pentru parametrii raportului.",
		preferences_wdw : "Preferinţe",
		remember_view_state : "Păstrează view state",
		upload_btn : "Trimite",
		upload_file : "Fişier",
		upload_name : "Nume",
		upload_title : "Upload fişier"
	},
	tlbitem : {
		autoload__lbl : "Auto",
		autoload__tlp : "Activează modul `auto` pentru incărcare automată a dependintelor.",
		back__lbl : "Înapoi",
		back__tlp : "Înapoi",
		cancel__lbl : "Anulează",
		cancel__tlp : "Anulează modificările utilizatorului.",
		clearFilter__lbl : "Sterge filtru",
		clearFilter__tlp : "Sterge filtru.",
		close__lbl : "Închide",
		close__tlp : "Închide",
		copy__lbl : "Copiază",
		copy__tlp : "Copiază înregistrarea curentă",
		delete_current__lbl : "Şterge",
		delete_current__tlp : "Şterge înregistrarea curentă",
		delete_selected__lbl : "Şterge",
		delete_selected__tlp : "Şterge înregistrările selectate",
		edit__lbl : "Modifică",
		edit__tlp : "Afisează formularul de modificare.",
		load__lbl : "Filtrează",
		load__tlp : "Încarcă înregistrările care corespund criteriilor de filtrare specificate.",
		new__lbl : "Crează",
		new__tlp : "Crează înregistrare nouă",
		next_rec__lbl : "Următor",
		next_rec__tlp : "Încarcă înregistrarea următoare din cele selectate sau următoare disponibilă dacă nu există selecţie multiplă",
		ok__lbl : "OK",
		ok__tlp : "OK",
		prev_rec__lbl : "Anterior",
		prev_rec__tlp : "Încarcă înregistrarea anterioară din cele selectate sau cea anterioră disponibilă dacă nu există selecţie multiplă",
		save__lbl : "Salvează",
		save__tlp : "Salvează modificările."
	}
};
