Ext.ns("dnet");
dnet.Translation = {
	appmenuitem : {
		about__lbl : "About DNet",
		appmenus__lbl : "Application menu",
		bookmark__lbl : "Bookmarks",
		calendar__lbl : "Calendar",
		changepswd__lbl : "Change password",
		client__lbl : "Client",
		frameInspector__lbl : "Frame inspector",
		help__lbl : "Help",
		home__lbl : "Home",
		lang__lbl : "Language",
		lock__lbl : "Lock",
		logout__lbl : "Logout",
		managebookmark__lbl : "Manage",
		myaccount__lbl : "My account",
		mysettings__lbl : "My settings",
		session__lbl : "Session",
		theme__lbl : "Theme",
		theme_access__lbl : "Black",
		theme_aqua__lbl : "Aqua",
		theme_blue__lbl : "Blue",
		theme_capuccino__lbl : "Capuccino",
		theme_gray__lbl : "Gray",
		user__lbl : "User",
		userprefs__lbl : "Preferences",
		version__lbl : "Version"
	},
	dcvgrid : {
		btn_bulkedit_tlp : "Bulk update selected records",
		btn_perspective_tlp : "Manage custom layouts",
		btn_perspective_txt : "Layout",
		bulkedit_run : "Apply changes",
		bulkedit_title : "Bulk update",
		exp_btn : "Export",
		exp_col_all : "All list columns",
		exp_col_all2 : "All available data",
		exp_col_visible : "Visible columns",
		exp_columns : "Columns",
		exp_format : "Format",
		exp_layout : "Layout",
		exp_rec_all : "All records",
		exp_rec_current : "Current record",
		exp_rec_sel : "Selected records",
		exp_records : "Records",
		exp_run : "Export",
		exp_title : "Export data",
		filter_apply : "Apply",
		filter_clear : "Clear",
		filter_title : "Advanced filter",
		imp_btn : "Import",
		imp_file : "File",
		imp_format : "Format",
		imp_notes : "The first line from the file is skipped. It is assumed to be the headers line.",
		imp_notes_lbl : "Notes",
		imp_run : "Run",
		imp_strgy : "Strategy",
		imp_strgy_bean : "Tehnical name( Fields in csv file have the same header as the grid data model - see export )",
		imp_strgy_pos : "Grid layout( Visible columns in grid match the fields in csv file in the same order )",
		imp_title : "Import data",
		layout_applySelected : "Apply selected",
		layout_mylayouts : "Select existing layout",
		layout_name : "Save current layout as",
		layout_saveCurrent : "Save current",
		layout_title : "My layouts",
		print_run : "Print",
		print_title : "Print data",
		sort_btn : "Sort",
		sort_run : "Apply",
		sort_title : "Sort by multiple fields"
	},
	ds : {
		active : "Active",
		bpartnerCode : "Business partner",
		bpartnerId : "Business partner(ID)",
		clientId : "Client",
		code : "Code",
		createdAt : "Created at",
		createdBy : "Created by",
		description : "Description",
		id : "ID",
		modifiedAt : "Modified at",
		modifiedBy : "Modified by",
		name : "Name",
		notes : "Notes",
		statusId : "Status(ID)",
		statusName : "Status",
		valid : "Valid",
		version : "Version"
	},
	exception : {
		DIRTY_DATA_FOUND : "Unsaved changes found. Save your changes or discard them.",
		NAVIGATE_AFTER_LAST : "At last available record.",
		NAVIGATE_BEFORE_FIRST : "At first available record.",
		NO_CURRENT_RECORD : "There is no current record to perform the requested action.",
		NO_SELECTED_RECORDS : "There are no selected records to perform the requested action.",
		PARENT_RECORD_NEW : "Parent record is new. Save or discard changes then try again."
	},
	msg : {
		bool_false : "No",
		bool_true : "Yes",
		chpswd_btn : "Change password",
		chpswd_nomatch : "The new password is not confirmed correctly. Re-enter `Confirm password` field.",
		chpswd_pswd1 : "New password",
		chpswd_pswd2 : "Confirm password",
		chpswd_success : "Password changed.<BR> Use the new password on next login.",
		chpswd_title : "Change password",
		dc_confirm_action : "Confirm action",
		dc_confirm_delete_selection : "Do you really want to delete the selected records? ",
		grid_emptytext : "No records found to match the specified selection criteria.",
		initialize : "Initializing",
		loading : "Loading",
		login_btn : "Login",
		login_client : "Client",
		login_lang : "Language",
		login_pswd : "Password",
		login_title : "Authentication",
		login_user : "User",
		no_current_record : "No current record",
		no_current_record_for_report : "There is no current record.<br> Cannot call report `{1}` without a current record which must provide  values for the report parameters.",
		preferences_wdw : "Preferences",
		remember_view_state : "Remember view state",
		upload_btn : "Upload",
		upload_file : "File",
		upload_name : "Name",
		upload_title : "Upload file"
	},
	tlbitem : {
		autoload__lbl : "Auto",
		autoload__tlp : "Toogle auto-load mode (Load data automatically when parent record is changed).",
		back__lbl : "Back",
		back__tlp : "Back to previous canvas.",
		cancel__lbl : "Cancel",
		cancel__tlp : "Cancel all changes made to all records since the last save or load.",
		clearFilter__lbl : "Clear filter",
		clearFilter__tlp : "Clear filter.",
		close__lbl : "Close",
		close__tlp : "Close",
		copy__lbl : "Copy",
		copy__tlp : "Create a copy of the current record.",
		delete_current__lbl : "Delete",
		delete_current__tlp : "Delete current record.",
		delete_selected__lbl : "Delete",
		delete_selected__tlp : "Delete selected records.",
		edit__lbl : "Edit",
		edit__tlp : "Toogle edit mode for the current record.",
		load__lbl : "Load",
		load__tlp : "Load records from database according to specified filter. ",
		new__lbl : "New",
		new__tlp : "Create new record",
		next_rec__lbl : "Next",
		next_rec__tlp : "Go to next selected record or next available record if no selection.",
		ok__lbl : "OK",
		ok__tlp : "OK",
		prev_rec__lbl : "Previous",
		prev_rec__tlp : "Go to previous selected record or previous available record if no selection.",
		save__lbl : "Save",
		save__tlp : "Save changes."
	}
};
